version: '3.8'

services:
  diagram-generator:
    build: .
    container_name: diagram-generator
    env_file:
      - .env
    environment:
      - DEFAULT_OUTPUT_DIR=/app/output
    volumes:
      - ./output:/app/output
    tty: true
    stdin_open: true
